
export default {
    initialState: {
        x: -16,
        y: -12,
        fixedSize: true,
        width: 1920,
        height: 1080,
        text: 'Expert',
        font: 'Volkart-Light:JeremieHornus:1.200',
        fontSize: 600,
        lineHeightFactor: 1.1,
        margin: 102,
        isMoving: false,
        startPos: null,
        numSplit: 32,
        colorExtrusion: 'black',
        colorBackground: 'white',
        colorForeground: 'white',
        extrusionLineWidth: 1,
        maskLineWidth: 4,
        version: 3,
    },
    fonts: [
        '/fonts/Volkart/Volkart-Light.otf',
        '/fonts/Volkart/Volkart-Regular.otf',
        '/fonts/Volkart/Volkart-Bold.otf',
        '/fonts/Volkart/Volkart-Extrabold.otf',
    ],
    palette: ['#ffffff', '#dde1e4', '#768692', '#000000', '#da291c'],
};
