
export default {
    initialState: {
        x: 64,
        y: 64,
        fixedSize: true,
        width: 1920,
        height: 1080,
        text: 'Welcome',
        font: null,
        fontSize: 300,
        lineHeightFactor: 1.16,
        margin: 0.2,
        isMoving: false,
        startPos: null,
        numSplit: 32,
        colorExtrusion: 'black',
        colorBackground: 'white',
        colorForeground: 'white',
        palette: ['black', 'white', 'red', 'green', 'blue']
    },
    fonts: [
        '/fonts/Volkart/Volkart-BlackItalic.otf',
        '/fonts/Volkart/Volkart-Black.otf',
        '/fonts/Volkart/Volkart-BoldItalic.otf',
        '/fonts/Volkart/Volkart-Bold.otf',
        '/fonts/Volkart/Volkart-ExtraboldItalic.otf',
        '/fonts/Volkart/Volkart-Extrabold.otf',
        '/fonts/Volkart/Volkart-ExtralightItalic.otf',
        '/fonts/Volkart/Volkart-Extralight.otf',
        '/fonts/Volkart/Volkart-HairlineItalic.otf',
        '/fonts/Volkart/Volkart-Hairline.otf',
        '/fonts/Volkart/Volkart-Italic.otf',
        '/fonts/Volkart/Volkart-LightItalic.otf',
        '/fonts/Volkart/Volkart-Light.otf',
        '/fonts/Volkart/Volkart-MediumItalic.otf',
        '/fonts/Volkart/Volkart-Medium.otf',
        '/fonts/Volkart/Volkart-Regular.otf',
        '/fonts/Volkart/Volkart-ThinItalic.otf',
        '/fonts/Volkart/Volkart-Thin.otf',
    ]
};
